### ISSUE TITLE
Gaya Penulisan Kode

### ISSUE THREAD

**Issue by jefrydco** [muh-hizbe/cari-teks-video#1]
Hi Mas Hizbullah, terima kasih sudah mengirimkan kode belajar Vue.js Fundamental, saya sangat mengapresiasi kerja keras Mas Hizbullah.

Luas biasa Mas, Mas sudah menerapkan banyak hal menarik pada aplikasi pencari teks di video yg Mas buat, termasuk di antaranya service worker dan PWA. Mas juga menambahkan Data Terstruktur berfomrmat JSON-LD.

1. Menambahkan Spasi antara `()` dan `{` pada Fungsi
Mungkin saran kecil dari saya agar Mas menambahkan spasi antara `()` dan `{` pada deklarasi fungsi. Sebagai contoh pada berkas `js/vue.js` pada baris 30 berikut:

https://github.com/muh-hizbe/cari-teks-video/blob/3c9076cb80450414e94ef438de7335797c7a7cd6/js/vue.js#L30

Akan lebih baik jika terdapat spasi seperti berikut:

```javascript
export default {
  methods: {
    resetKey() {
       // Kode di dalamnya
    }
  }
}
```

Pada bagian lain Mas juga sudah menerapkan hal tersebut, seperti pada baris 18 berikut:

https://github.com/muh-hizbe/cari-teks-video/blob/3c9076cb80450414e94ef438de7335797c7a7cd6/js/vue.js#L18

Antara `query(query)` dan `{` sudah terdapat spasi.

2. Memformat Fungsi Panah
Kemudian pada fungsi panah untuk parameter `setTimeout` pada baris ke 23 berikut sepertinya belum terformat dengan baik Mas:

https://github.com/muh-hizbe/cari-teks-video/blob/3c9076cb80450414e94ef438de7335797c7a7cd6/js/vue.js#L23-L27

Mungkin akan lebih baik jika formatnya seperti berikut Mas:

```javascript
setTimeout(() => {
  // Kode di dalamnya
}, 1000)
```

---

Walaupun terlihat sepeleh, namun menurut saya akan sangat berguna Mas untuk kedepannya nanti. Apalagi jika nanti sudah bekerja dalam tim, bahkan bisa kita menganggap suatu kode hanya ditulis oleh satu orang karena keseragamannya.

Lebih lanjut Mas dapat membaca pada tautan berikut: [Mozilla Developer Network - JavaScript Guidelines](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines/JavaScript#Functions_and_objects)

Semangat Mas! 😄

**Comment by muh-hizbe** [comment]
Terimakasih atas feedback dan sarannya mas, nanti akan saya perbaiki cara
penulisannya, izin bertanya mas adakah standart penulisan javascript yg
diberlakukan dalam skala global atau yg disepakati oleh sebagai standart yg
diakui oleh kalangan javascript developer? Kalo ada bisa kasih link untuk
saya pelajari.

**Comment by jefrydco** [comment]
Hi Mas, untuk standar penulisan JavaScript pada umumnya kita bisa menggunakan perangkat lunak bernama [Eslint](https://eslint.org/). Eslint tersebut akan memaksa kita untuk menulis kode dengan gaya penulisan tertentu yg telah kita atur sebelumnya. Bahka kita juga dapat mengatur agar ketika kita menuliskan gaya penulisan kode yg tidak sesuai, Eslint akan memperbaikinya secara otomatis.

Untuk gaya penulisannya sendiri ada beberapa yg biasa dipakai Mas, [Google JavaScript Styleguide](https://github.com/google/styleguide), [AirBnB JavaScript Styleguide](https://github.com/airbnb/javascript), [JavaScript Standard Styleguide](https://github.com/standard/eslint-config-standard).

Kalau sudah menggunakan Eslint kita tidak perlu lagi mengingat-ngingat aturan gaya penulisannya karena sudah di tangani oleh Eslintnya.

Semangat Mas! 😄

**Comment by muh-hizbe** [comment]
Oke terimakasih mas
